### ISSUE TITLE
Address Security findings

### ISSUE THREAD

**Issue by ErikRehmTT** [jenkinsci/ecu-test-execution-plugin#187]
## Description

With the introduction of the `Jenkins Security Scan` action, we got some findings in the generated API clients. As a security aware maintainer I want to have a secure plugin and take them serious.

## Acceptance Criteria

- [x] Security findings were addressed
- [x] Security tab does not contain findings

## Additional Information

- check if generation could be done without auth implementations for example
- mark a finding as false-positive or won't fix if the concern is not valid

**Comment by MxEh-TT** [comment]
Issues mainly caused by parts of the generated openapi template, which are always included, but not necessarily used.
Additionaly the TGUploadOrder uses a authKey field which is serializable but should not be saved anywhere.

Fixing this would require defining/adjusting the openapi template, which is not in the scope of this issue.
